import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font, Image } from '@react-pdf/renderer';

// Register Fonts with error handling
// Using standard fallbacks if font loading fails
try {
  Font.register({
    family: 'Cormorant Garamond',
    fonts: [
      { src: 'https://fonts.gstatic.com/s/cormorantgaramond/v16/co3BmX5slCNuHLi8bLeY9MK7whWMhyjYpHtK.ttf' }, // Regular
      { src: 'https://fonts.gstatic.com/s/cormorantgaramond/v16/co3YmX5slCNuHLi8bLeY9MK7whWMhyjYpHtKky2F.ttf', fontWeight: 700 }, // Bold
      { src: 'https://fonts.gstatic.com/s/cormorantgaramond/v16/co3ZmX5slCNuHLi8bLeY9MK7whWMhyjYpHtKkyaTjg.ttf', fontStyle: 'italic' }, // Italic
    ],
  });
} catch (e) {
  console.warn('Failed to register Cormorant Garamond font:', e);
}

try {
  Font.register({
    family: 'Lato',
    fonts: [
      { src: 'https://fonts.gstatic.com/s/lato/v24/S6uyw4BMUTPHjx4wXg.ttf' }, // Regular
      { src: 'https://fonts.gstatic.com/s/lato/v24/S6u9w4BMUTPHh6UVSwiPHA.ttf', fontWeight: 700 }, // Bold
    ],
  });
} catch (e) {
  console.warn('Failed to register Lato font:', e);
}

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#FDFBF7', // Madison "Vellum"
    padding: 40,
    fontFamily: 'Lato',
  },
  section: {
    margin: 10,
    padding: 10,
  },
  coverPage: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FDFBF7',
  },
  logoText: {
    fontFamily: 'Cormorant Garamond',
    fontSize: 40,
    fontWeight: 700,
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: '#1A1816', // Ink Black
    marginBottom: 20,
  },
  subtitle: {
    fontFamily: 'Lato',
    fontSize: 12,
    letterSpacing: 3,
    textTransform: 'uppercase',
    color: '#B8956A', // Aged Brass
  },
  header: {
    fontFamily: 'Cormorant Garamond',
    fontSize: 24,
    fontWeight: 700,
    marginBottom: 10,
    color: '#1A1816',
    borderBottom: '1px solid #E5DFD1',
    paddingBottom: 5,
  },
  subHeader: {
    fontFamily: 'Lato',
    fontSize: 10,
    fontWeight: 700,
    textTransform: 'uppercase',
    color: '#B8956A',
    marginTop: 15,
    marginBottom: 5,
  },
  text: {
    fontSize: 11,
    lineHeight: 1.6,
    color: '#2F2A26', // Charcoal
    marginBottom: 8,
  },
  tag: {
    backgroundColor: '#E5DFD1',
    padding: '4 8',
    borderRadius: 4,
    marginRight: 5,
    marginBottom: 5,
    fontSize: 10,
  },
  tagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  divider: {
    borderBottom: '1px solid #E5DFD1',
    marginVertical: 20,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 9,
    color: '#999',
  },
});

interface BrandBookProps {
  brandName: string;
  brandData: any; // The structured JSON from the scraper
}

export const BrandBookPDF = ({ brandName, brandData }: BrandBookProps) => (
  <Document>
    {/* COVER PAGE */}
    <Page size="A4" style={styles.coverPage}>
      <Text style={styles.logoText}>{brandName}</Text>
      <Text style={styles.subtitle}>Brand Identity & Voice Guidelines</Text>
      <Text style={{ position: 'absolute', bottom: 50, fontSize: 10, color: '#999' }}>
        Generated by Madison Studio
      </Text>
    </Page>

    {/* CORE IDENTITY */}
    <Page size="A4" style={styles.page}>
      <View style={styles.section}>
        <Text style={styles.header}>Core Identity</Text>
        
        {brandData.brand_identity?.mission && (
          <>
            <Text style={styles.subHeader}>Mission Statement</Text>
            <Text style={[styles.text, { fontFamily: 'Cormorant Garamond', fontSize: 14, fontStyle: 'italic' }]}>
              "{brandData.brand_identity.mission}"
            </Text>
          </>
        )}

        <Text style={styles.subHeader}>Core Values</Text>
        <View style={styles.tagsRow}>
          {brandData.brand_identity?.values && Array.isArray(brandData.brand_identity.values) && brandData.brand_identity.values.length > 0 ? (
            brandData.brand_identity.values.map((val: string, i: number) => (
              <View key={i} style={styles.tag}><Text>{val}</Text></View>
            ))
          ) : (
            <Text style={styles.text}>Not defined</Text>
          )}
        </View>

        <Text style={styles.subHeader}>Target Audience</Text>
        <Text style={styles.text}>{brandData.brand_identity?.target_audience || 'Not defined'}</Text>
      </View>

      <View style={styles.divider} />

      <View style={styles.section}>
        <Text style={styles.header}>Brand Voice</Text>
        
        <Text style={styles.subHeader}>Tone Characteristics</Text>
        <View style={styles.tagsRow}>
          {brandData.brand_voice?.tone && Array.isArray(brandData.brand_voice.tone) && brandData.brand_voice.tone.length > 0 ? (
            brandData.brand_voice.tone.map((t: string, i: number) => (
              <View key={i} style={[styles.tag, { backgroundColor: '#F0EBE0' }]}><Text>{t}</Text></View>
            ))
          ) : (
            <Text style={styles.text}>Not defined</Text>
          )}
        </View>

        <Text style={styles.subHeader}>Writing Style</Text>
        <Text style={styles.text}>{brandData.brand_voice?.style}</Text>
        
        <Text style={styles.subHeader}>Perspective</Text>
        <Text style={styles.text}>{brandData.brand_voice?.perspective}</Text>
      </View>

      <Text style={styles.footer}>Page 2 • Confidential Brand Guidelines</Text>
    </Page>

    {/* VOCABULARY & STRATEGY */}
    <Page size="A4" style={styles.page}>
      <View style={styles.section}>
        <Text style={styles.header}>Strategic Brand Audit</Text>
        <Text style={styles.subHeader}>Executive Summary</Text>
        <Text style={styles.text}>{brandData.strategic_audit?.summary || 'No strategic audit data available.'}</Text>

        <View style={{ flexDirection: 'row', gap: 20, marginTop: 10 }}>
          <View style={{ flex: 1 }}>
            <Text style={styles.subHeader}>Strengths</Text>
            {brandData.strategic_audit?.strengths?.map((s: string, i: number) => (
              <Text key={i} style={[styles.text, { color: '#166534' }]}>+ {s}</Text>
            ))}
          </View>
          <View style={{ flex: 1 }}>
            <Text style={styles.subHeader}>Weaknesses & Gaps</Text>
            {brandData.strategic_audit?.weaknesses?.map((w: string, i: number) => (
              <Text key={i} style={[styles.text, { color: '#991B1B' }]}>- {w}</Text>
            ))}
          </View>
        </View>

        <Text style={styles.subHeader}>Growth Opportunities (Leverage)</Text>
        {brandData.strategic_audit?.opportunities?.map((op: string, i: number) => (
          <Text key={i} style={styles.text}>→ {op}</Text>
        ))}
      </View>

      <View style={styles.divider} />

      <View style={styles.section}>
        <Text style={styles.header}>Vocabulary</Text>
        
        <Text style={styles.subHeader}>Keywords to Use</Text>
        <View style={styles.tagsRow}>
          {brandData.vocabulary?.keywords && Array.isArray(brandData.vocabulary.keywords) && brandData.vocabulary.keywords.length > 0 ? (
            brandData.vocabulary.keywords.map((word: string, i: number) => (
              <View key={i} style={[styles.tag, { backgroundColor: '#E6F4EA', color: '#166534' }]}><Text>✓ {word}</Text></View>
            ))
          ) : (
            <Text style={styles.text}>Not defined</Text>
          )}
        </View>

        <Text style={styles.subHeader}>Key Phrases</Text>
        {brandData.vocabulary?.phrases && Array.isArray(brandData.vocabulary.phrases) && brandData.vocabulary.phrases.length > 0 ? (
          brandData.vocabulary.phrases.map((phrase: string, i: number) => (
            <Text key={i} style={styles.text}>• "{phrase}"</Text>
          ))
        ) : (
          <Text style={styles.text}>Not defined</Text>
        )}

        {brandData.vocabulary?.forbidden_inferred && Array.isArray(brandData.vocabulary.forbidden_inferred) && brandData.vocabulary.forbidden_inferred.length > 0 && (
          <>
            <Text style={styles.subHeader}>Avoid These (Off-Brand)</Text>
            <View style={styles.tagsRow}>
              {brandData.vocabulary.forbidden_inferred.map((word: string, i: number) => (
                <View key={i} style={[styles.tag, { backgroundColor: '#FEE2E2', color: '#991B1B' }]}><Text>✗ {word}</Text></View>
              ))}
            </View>
          </>
        )}
      </View>

      <Text style={styles.footer}>Page 3 • Confidential Brand Guidelines</Text>
    </Page>

    {/* CONTENT STRATEGY */}
    <Page size="A4" style={styles.page}>
      <View style={styles.section}>
        <Text style={styles.header}>Content Strategy</Text>
        
        <Text style={styles.subHeader}>Core Themes</Text>
        <View style={styles.tagsRow}>
          {brandData.content_strategy?.themes?.map((theme: string, i: number) => (
            <View key={i} style={styles.tag}><Text>{theme}</Text></View>
          ))}
        </View>

        <Text style={styles.subHeader}>Narrative Hooks</Text>
        {brandData.content_strategy?.hooks?.map((hook: string, i: number) => (
          <Text key={i} style={styles.text}>• {hook}</Text>
        ))}
      </View>
      <Text style={styles.footer}>Page 4 • Confidential Brand Guidelines</Text>
    </Page>
  </Document>
);

