import React from 'react';
import { BrandReport } from '@/types/brandReport';

interface BrandReportTemplateProps {
  report: BrandReport;
  domain: string;
}

/**
 * Agency-Quality Brand Report Template
 * 
 * Uses mapsystem.io design tokens as base.
 * Scanned brand colors used as accents/swatches only.
 * Consistent spacing, type scale, and layout.
 */
export function BrandReportTemplate({ report, domain }: BrandReportTemplateProps) {
  const brandName = report.brandProfile.brandName || domain;
  const logoUrl = report.site.logoUrl;
  const primaryColor = report.colors.primary[0] || '#B8956A';
  const tagline = report.brandProfile.tagline;
  const positioning = report.brandProfile.positioning;
  
  // Calculate scores (if not provided, generate from data completeness)
  const brandConsistency = report.scoring?.brandConsistency ?? calculateBrandConsistency(report);
  const visualConsistency = report.scoring?.visualConsistency ?? calculateVisualConsistency(report);
  const messageClarity = report.scoring?.messageClarity ?? calculateMessageClarity(report);
  const overallScore = report.scoring?.overallScore ?? Math.round((brandConsistency + visualConsistency + messageClarity) / 3);

  return (
    <div className="brand-report min-h-screen bg-vellum-cream">
      {/* Cover Page */}
      <div className="min-h-screen bg-gradient-to-br from-vellum-cream via-parchment-white to-vellum-cream flex flex-col items-center justify-center p-12 print:min-h-0 print:page-break-after-always">
        <div className="text-center max-w-3xl w-full">
          {/* Client Logo */}
          {logoUrl && (
            <div className="mb-12">
              <img 
                src={logoUrl} 
                alt={brandName} 
                className="h-32 mx-auto object-contain max-w-md"
                style={{ maxHeight: '128px' }}
              />
            </div>
          )}
          
          {/* Brand Name */}
          <h1 className="text-7xl md:text-8xl font-serif text-ink-black mb-6 leading-tight">
            {brandName}
          </h1>
          
          {/* Domain */}
          <p className="text-xl text-charcoal/60 mb-8 font-mono">
            {report.site.domain}
          </p>
          
          {/* Tagline (if present) */}
          {tagline && (
            <p className="text-2xl text-charcoal/80 italic mb-12 max-w-2xl mx-auto">
              "{tagline}"
            </p>
          )}
          
          {/* Divider */}
          <div className="w-24 h-0.5 bg-brass mx-auto mb-12" />
          
          {/* mapsystem.io Branding */}
          <div className="space-y-2">
            <p className="text-sm font-serif text-ink-black tracking-widest uppercase">
              Brand Audit Report
            </p>
            <p className="text-xs text-charcoal/50">
              Generated by <span className="font-semibold">mapsystem.io</span>
            </p>
            <p className="text-xs text-charcoal/40 mt-4">
              {new Date(report.scanMeta.scannedAt).toLocaleDateString('en-US', { 
                year: 'numeric', 
                month: 'long', 
                day: 'numeric' 
              })}
            </p>
          </div>
        </div>
      </div>

      {/* Section 1: Snapshot */}
      <div className="bg-parchment-white p-8 md:p-12 lg:p-16 print:page-break-after-always">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-5xl font-serif text-ink-black mb-12 border-b-2 border-brass pb-6">
            Snapshot
          </h2>
          
          <div className="grid md:grid-cols-2 gap-12 mb-12">
            {/* Logo & Brand Name */}
            <div>
              <h3 className="text-xs font-semibold uppercase tracking-wider text-brass mb-4">
                Brand Identity
              </h3>
              {logoUrl && (
                <div className="mb-6">
                  <img 
                    src={logoUrl} 
                    alt={brandName} 
                    className="h-20 object-contain mb-4"
                  />
                </div>
              )}
              <h4 className="text-3xl font-serif text-ink-black mb-2">{brandName}</h4>
              {tagline && (
                <p className="text-lg text-charcoal/80 italic">{tagline}</p>
              )}
            </div>
            
            {/* Quick Scores */}
            <div>
              <h3 className="text-xs font-semibold uppercase tracking-wider text-brass mb-4">
                Brand Health Scores
              </h3>
              <div className="space-y-4">
                <ScoreBar label="Brand Consistency" value={brandConsistency} />
                <ScoreBar label="Visual Consistency" value={visualConsistency} />
                <ScoreBar label="Message Clarity" value={messageClarity} />
                <div className="pt-4 border-t border-charcoal/10">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-sm font-semibold text-ink-black">Overall Score</span>
                    <span className="text-2xl font-serif text-ink-black">{overallScore}</span>
                  </div>
                  <div className="w-full bg-charcoal/10 rounded-full h-3">
                    <div 
                      className="bg-brass h-3 rounded-full transition-all"
                      style={{ width: `${overallScore}%` }}
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
          
          {/* Positioning Statement */}
          {positioning && (
            <div className="bg-vellum-cream p-6 rounded-lg border border-charcoal/10">
              <h3 className="text-xs font-semibold uppercase tracking-wider text-brass mb-3">
                Positioning Statement
              </h3>
              <p className="text-charcoal leading-relaxed text-lg">
                {positioning}
              </p>
            </div>
          )}
        </div>
      </div>

      {/* Section 2: Brand Identity */}
      <div className="bg-vellum-cream p-8 md:p-12 lg:p-16 print:page-break-after-always">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-5xl font-serif text-ink-black mb-12 border-b-2 border-brass pb-6">
            Brand Identity
          </h2>
          
          <div className="grid md:grid-cols-2 gap-12">
            {/* Brand Profile */}
            <div>
              <h3 className="text-xs font-semibold uppercase tracking-wider text-brass mb-6">
                Brand Profile
              </h3>
              
              {report.brandProfile.mission && (
                <div className="mb-6">
                  <p className="text-xs text-charcoal/60 mb-2">Mission</p>
                  <p className="text-charcoal leading-relaxed italic">
                    "{report.brandProfile.mission}"
                  </p>
                </div>
              )}
              
              {report.brandProfile.values && report.brandProfile.values.length > 0 && (
                <div className="mb-6">
                  <p className="text-xs text-charcoal/60 mb-2">Core Values</p>
                  <div className="flex flex-wrap gap-2">
                    {report.brandProfile.values.map((val, i) => (
                      <span
                        key={i}
                        className="px-3 py-1.5 bg-parchment-white text-charcoal rounded-full text-xs font-medium border border-charcoal/10"
                      >
                        {val}
                      </span>
                    ))}
                  </div>
                </div>
              )}
              
              {report.brandProfile.primaryAudience && report.brandProfile.primaryAudience.length > 0 && (
                <div className="mb-6">
                  <p className="text-xs text-charcoal/60 mb-2">Primary Audience</p>
                  <ul className="space-y-1">
                    {report.brandProfile.primaryAudience.map((audience, i) => (
                      <li key={i} className="text-charcoal text-sm">• {audience}</li>
                    ))}
                  </ul>
                </div>
              )}
              
              {report.brandProfile.archetype && (
                <div>
                  <p className="text-xs text-charcoal/60 mb-2">Brand Archetype</p>
                  <p className="text-lg font-serif text-ink-black">{report.brandProfile.archetype}</p>
                </div>
              )}
            </div>
            
            {/* Tone & Voice */}
            <div>
              <h3 className="text-xs font-semibold uppercase tracking-wider text-brass mb-6">
                Tone & Voice
              </h3>
              
              {report.brandVoice?.tone && report.brandVoice.tone.length > 0 && (
                <div className="mb-6">
                  <p className="text-xs text-charcoal/60 mb-3">Tone Traits</p>
                  <div className="flex flex-wrap gap-2">
                    {report.brandVoice.tone.map((trait, i) => (
                      <span
                        key={i}
                        className="px-3 py-1.5 bg-parchment-white text-charcoal rounded-full text-xs font-medium border border-charcoal/10"
                      >
                        {trait}
                      </span>
                    ))}
                  </div>
                </div>
              )}
              
              {report.brandVoice?.style && (
                <div className="mb-6">
                  <p className="text-xs text-charcoal/60 mb-2">Writing Style</p>
                  <p className="text-charcoal leading-relaxed text-sm">{report.brandVoice.style}</p>
                </div>
              )}
              
              {report.brandVoice?.perspective && (
                <div className="mb-6">
                  <p className="text-xs text-charcoal/60 mb-2">Perspective</p>
                  <p className="text-charcoal text-sm">{report.brandVoice.perspective}</p>
                </div>
              )}
              
              {report.brandProfile.essence && (
                <div>
                  <p className="text-xs text-charcoal/60 mb-2">Brand Essence</p>
                  <p className="text-charcoal text-sm font-medium">{report.brandProfile.essence}</p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Section 3: Visual Language */}
      <div className="bg-parchment-white p-8 md:p-12 lg:p-16 print:page-break-after-always">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-5xl font-serif text-ink-black mb-12 border-b-2 border-brass pb-6">
            Visual Language
          </h2>
          
          {/* Color Palette */}
          {(report.colors.primary.length > 0 || report.colors.secondary.length > 0 || report.colors.neutrals.length > 0) && (
            <div className="mb-12">
              <h3 className="text-xs font-semibold uppercase tracking-wider text-brass mb-6">
                Color Palette
              </h3>
              
              {/* Primary Colors */}
              {report.colors.primary.length > 0 && (
                <div className="mb-8">
                  <p className="text-sm text-charcoal/70 mb-4">Primary Colors</p>
                  <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-4">
                    {report.colors.primary.map((hex, i) => (
                      <ColorSwatch key={i} hex={hex} label={`Primary ${i + 1}`} />
                    ))}
                  </div>
                </div>
              )}
              
              {/* Secondary Colors */}
              {report.colors.secondary.length > 0 && (
                <div className="mb-8">
                  <p className="text-sm text-charcoal/70 mb-4">Secondary Colors</p>
                  <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-4">
                    {report.colors.secondary.map((hex, i) => (
                      <ColorSwatch key={i} hex={hex} label={`Secondary ${i + 1}`} />
                    ))}
                  </div>
                </div>
              )}
              
              {/* Neutral Colors */}
              {report.colors.neutrals.length > 0 && (
                <div className="mb-8">
                  <p className="text-sm text-charcoal/70 mb-4">Neutral Colors</p>
                  <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-4">
                    {report.colors.neutrals.map((hex, i) => (
                      <ColorSwatch key={i} hex={hex} label={`Neutral ${i + 1}`} />
                    ))}
                  </div>
                </div>
              )}
              
              {/* Color Commentary */}
              <div className="bg-vellum-cream p-6 rounded-lg border border-charcoal/10 mt-8">
                <p className="text-xs font-semibold uppercase tracking-wider text-brass mb-2">
                  Color Analysis
                </p>
                <p className="text-sm text-charcoal leading-relaxed">
                  {generateColorCommentary(report.colors)}
                </p>
              </div>
            </div>
          )}
          
          {/* Typography */}
          {report.typography && (
            <div>
              <h3 className="text-xs font-semibold uppercase tracking-wider text-brass mb-6">
                Typography
              </h3>
              <div className="grid md:grid-cols-2 gap-8">
                {report.typography.headlineFont && (
                  <div>
                    <p className="text-xs text-charcoal/60 mb-3">Headline Font</p>
                    <p 
                      className="text-4xl font-serif text-ink-black mb-2"
                      style={{ fontFamily: report.typography.headlineFont }}
                    >
                      {report.typography.headlineFont}
                    </p>
                    <p className="text-xs text-charcoal/50 font-mono">{report.typography.headlineFont}</p>
                  </div>
                )}
                {report.typography.bodyFont && (
                  <div>
                    <p className="text-xs text-charcoal/60 mb-3">Body Font</p>
                    <p 
                      className="text-xl text-charcoal leading-relaxed mb-2"
                      style={{ fontFamily: report.typography.bodyFont }}
                    >
                      {report.typography.bodyFont}
                    </p>
                    <p className="text-xs text-charcoal/50 font-mono">{report.typography.bodyFont}</p>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Section 4: Messaging & Website Copy Assessment */}
      <div className="bg-vellum-cream p-8 md:p-12 lg:p-16 print:page-break-after-always">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-5xl font-serif text-ink-black mb-12 border-b-2 border-brass pb-6">
            Messaging & Copy Assessment
          </h2>
          
          {/* Vocabulary */}
          {report.brandVoice?.vocabulary && (
            <div className="mb-12">
              <h3 className="text-xs font-semibold uppercase tracking-wider text-brass mb-6">
                Vocabulary
              </h3>
              
              {report.brandVoice.vocabulary.keywords && report.brandVoice.vocabulary.keywords.length > 0 && (
                <div className="mb-8">
                  <p className="text-sm text-charcoal/70 mb-4">Keywords to Use</p>
                  <div className="flex flex-wrap gap-2">
                    {report.brandVoice.vocabulary.keywords.map((word, i) => (
                      <span
                        key={i}
                        className="px-3 py-1.5 bg-green-50 text-green-800 rounded-full text-xs font-medium border border-green-200"
                      >
                        ✓ {word}
                      </span>
                    ))}
                  </div>
                </div>
              )}
              
              {report.brandVoice.vocabulary.phrases && report.brandVoice.vocabulary.phrases.length > 0 && (
                <div className="mb-8">
                  <p className="text-sm text-charcoal/70 mb-4">Key Phrases</p>
                  <ul className="space-y-2">
                    {report.brandVoice.vocabulary.phrases.map((phrase, i) => (
                      <li key={i} className="text-charcoal text-sm flex items-start">
                        <span className="text-brass mr-2">•</span>
                        <span>"{phrase}"</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
              
              {report.brandVoice.vocabulary.forbidden && report.brandVoice.vocabulary.forbidden.length > 0 && (
                <div>
                  <p className="text-sm text-charcoal/70 mb-4">Avoid These (Off-Brand)</p>
                  <div className="flex flex-wrap gap-2">
                    {report.brandVoice.vocabulary.forbidden.map((word, i) => (
                      <span
                        key={i}
                        className="px-3 py-1.5 bg-red-50 text-red-800 rounded-full text-xs font-medium border border-red-200"
                      >
                        ✗ {word}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
          
          {/* Content Strategy */}
          {report.contentStrategy && (
            <div>
              <h3 className="text-xs font-semibold uppercase tracking-wider text-brass mb-6">
                Content Strategy
              </h3>
              
              {report.contentStrategy.themes && report.contentStrategy.themes.length > 0 && (
                <div className="mb-8">
                  <p className="text-sm text-charcoal/70 mb-4">Core Themes</p>
                  <div className="flex flex-wrap gap-2">
                    {report.contentStrategy.themes.map((theme, i) => (
                      <span
                        key={i}
                        className="px-3 py-1.5 bg-parchment-white text-charcoal rounded-full text-xs font-medium border border-charcoal/10"
                      >
                        {theme}
                      </span>
                    ))}
                  </div>
                </div>
              )}
              
              {report.contentStrategy.hooks && report.contentStrategy.hooks.length > 0 && (
                <div>
                  <p className="text-sm text-charcoal/70 mb-4">Narrative Hooks</p>
                  <ul className="space-y-2">
                    {report.contentStrategy.hooks.map((hook, i) => (
                      <li key={i} className="text-charcoal text-sm flex items-start">
                        <span className="text-brass mr-2">→</span>
                        <span>{hook}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Section 5: Recommendations */}
      <div className="bg-parchment-white p-8 md:p-12 lg:p-16">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-5xl font-serif text-ink-black mb-12 border-b-2 border-brass pb-6">
            Recommendations & Next Steps
          </h2>
          
          {report.recommendations && report.recommendations.length > 0 ? (
            <div className="space-y-6">
              {report.recommendations.map((rec, i) => (
                <RecommendationCard key={i} recommendation={rec} />
              ))}
            </div>
          ) : (
            <div className="bg-vellum-cream p-8 rounded-lg border border-charcoal/10">
              <p className="text-charcoal leading-relaxed">
                Based on this brand audit, consider focusing on:
              </p>
              <ul className="mt-4 space-y-2 text-charcoal">
                {generateDefaultRecommendations(report).map((rec, i) => (
                  <li key={i} className="flex items-start">
                    <span className="text-brass mr-2">→</span>
                    <span>{rec}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </div>

      {/* Print Styles */}
      <style>{`
        @media print {
          .brand-report {
            background: white;
          }
          .print\\:page-break-after-always {
            page-break-after: always;
          }
          .print\\:min-h-0 {
            min-height: 0;
          }
        }
      `}</style>
    </div>
  );
}

/**
 * Score Bar Component
 */
function ScoreBar({ label, value }: { label: string; value: number }) {
  return (
    <div>
      <div className="flex items-center justify-between mb-1">
        <span className="text-xs text-charcoal/70">{label}</span>
        <span className="text-sm font-semibold text-ink-black">{value}</span>
      </div>
      <div className="w-full bg-charcoal/10 rounded-full h-2">
        <div 
          className="bg-brass h-2 rounded-full transition-all"
          style={{ width: `${value}%` }}
        />
      </div>
    </div>
  );
}

/**
 * Color Swatch Component
 */
function ColorSwatch({ hex, label }: { hex: string; label: string }) {
  return (
    <div className="bg-parchment-white rounded-lg p-4 shadow-sm border border-charcoal/10">
      <div
        className="w-full h-32 rounded mb-3 border border-charcoal/10"
        style={{ backgroundColor: hex }}
      />
      <p className="text-xs font-mono text-charcoal mb-1">{hex}</p>
      <p className="text-xs text-charcoal/60">{label}</p>
    </div>
  );
}

/**
 * Recommendation Card Component
 */
function RecommendationCard({ recommendation }: { recommendation: BrandReport['recommendations'][0] }) {
  const priorityColors = {
    high: 'bg-red-50 border-red-200 text-red-900',
    medium: 'bg-yellow-50 border-yellow-200 text-yellow-900',
    low: 'bg-blue-50 border-blue-200 text-blue-900',
  };
  
  return (
    <div className={`p-6 rounded-lg border ${priorityColors[recommendation.priority] || 'bg-vellum-cream border-charcoal/10'}`}>
      <div className="flex items-start justify-between mb-3">
        <h4 className="text-lg font-semibold text-ink-black">{recommendation.title}</h4>
        <span className="text-xs font-semibold uppercase tracking-wider px-2 py-1 rounded">
          {recommendation.priority}
        </span>
      </div>
      <p className="text-sm text-charcoal leading-relaxed mb-2">{recommendation.description}</p>
      {recommendation.category && (
        <span className="text-xs text-charcoal/60">{recommendation.category}</span>
      )}
    </div>
  );
}

/**
 * Generate color commentary
 */
function generateColorCommentary(colors: BrandReport['colors']): string {
  const totalColors = colors.primary.length + colors.secondary.length + colors.neutrals.length;
  
  if (totalColors === 0) {
    return 'No color palette was extracted from this website. Consider manually adding brand colors.';
  }
  
  const hasPrimary = colors.primary.length > 0;
  const hasSecondary = colors.secondary.length > 0;
  const hasNeutrals = colors.neutrals.length > 0;
  
  let commentary = `This brand uses a ${totalColors}-color palette. `;
  
  if (hasPrimary && colors.primary.length >= 3) {
    commentary += `The primary palette is well-defined with ${colors.primary.length} colors, suggesting a strong visual identity. `;
  }
  
  if (hasNeutrals && colors.neutrals.length >= 2) {
    commentary += `Neutral colors provide a solid foundation for backgrounds and text. `;
  }
  
  if (colors.colorSource === 'brandfetch') {
    commentary += 'Colors were extracted from a brand API, ensuring high accuracy.';
  } else if (colors.colorSource === 'css_parsing') {
    commentary += 'Colors were extracted from CSS, reflecting the actual implementation.';
  } else {
    commentary += 'Colors were extracted through automated analysis.';
  }
  
  return commentary;
}

/**
 * Calculate brand consistency score
 */
function calculateBrandConsistency(report: BrandReport): number {
  let score = 0;
  let factors = 0;
  
  if (report.brandProfile.brandName) { score += 20; factors++; }
  if (report.brandProfile.positioning) { score += 20; factors++; }
  if (report.brandProfile.mission) { score += 15; factors++; }
  if (report.brandProfile.values && report.brandProfile.values.length > 0) { score += 15; factors++; }
  if (report.brandProfile.primaryAudience && report.brandProfile.primaryAudience.length > 0) { score += 15; factors++; }
  if (report.brandVoice?.tone && report.brandVoice.tone.length > 0) { score += 15; factors++; }
  
  return factors > 0 ? Math.round(score / factors) : 50;
}

/**
 * Calculate visual consistency score
 */
function calculateVisualConsistency(report: BrandReport): number {
  let score = 0;
  let factors = 0;
  
  if (report.site.logoUrl) { score += 30; factors++; }
  if (report.colors.primary.length > 0) { score += 25; factors++; }
  if (report.colors.primary.length >= 3) { score += 10; factors++; }
  if (report.colors.neutrals.length > 0) { score += 15; factors++; }
  if (report.typography?.headlineFont) { score += 10; factors++; }
  if (report.typography?.bodyFont) { score += 10; factors++; }
  
  return factors > 0 ? Math.round(score / factors) : 50;
}

/**
 * Calculate message clarity score
 */
function calculateMessageClarity(report: BrandReport): number {
  let score = 0;
  let factors = 0;
  
  if (report.brandProfile.tagline) { score += 25; factors++; }
  if (report.brandProfile.positioning) { score += 25; factors++; }
  if (report.brandVoice?.vocabulary?.keywords && report.brandVoice.vocabulary.keywords.length > 0) { score += 20; factors++; }
  if (report.brandVoice?.vocabulary?.phrases && report.brandVoice.vocabulary.phrases.length > 0) { score += 15; factors++; }
  if (report.contentStrategy?.themes && report.contentStrategy.themes.length > 0) { score += 15; factors++; }
  
  return factors > 0 ? Math.round(score / factors) : 50;
}

/**
 * Generate default recommendations
 */
function generateDefaultRecommendations(report: BrandReport): string[] {
  const recommendations: string[] = [];
  
  if (!report.site.logoUrl) {
    recommendations.push('Upload a high-resolution logo to strengthen brand recognition');
  }
  
  if (report.colors.primary.length < 3) {
    recommendations.push('Define a more comprehensive color palette (3-5 primary colors)');
  }
  
  if (!report.brandProfile.tagline) {
    recommendations.push('Develop a clear tagline that communicates your brand promise');
  }
  
  if (!report.brandProfile.positioning) {
    recommendations.push('Clarify your brand positioning statement to differentiate from competitors');
  }
  
  if (!report.brandVoice?.vocabulary?.keywords || report.brandVoice.vocabulary.keywords.length < 5) {
    recommendations.push('Establish a brand vocabulary guide with 10-15 key terms');
  }
  
  if (recommendations.length === 0) {
    recommendations.push('Continue refining brand consistency across all touchpoints');
    recommendations.push('Document brand guidelines to ensure team alignment');
  }
  
  return recommendations;
}
